### ISSUE TITLE
Custom sort / filter 

### ISSUE THREAD

**Issue by dshlai** [4degrees/riffle#7]
Great project!

I notice in the code there is a QSortFilterProxyModel that is used to sort the items in the file system model. I want to use that to do my own custom sorting / filtering when creating the browser. (e.g., filter out certain unwanted directories that should be invisible to the user) 

Is there a API for accessing that model? Or I can access that model directly using QT's native method(e.g., setFilterRegExp()?)

**Comment by martinpengellyphillips** [comment]
Thanks!

Apologies for slow response. Did you get anywhere with this?

If you subclass the `FilesystemBrowser`, then you can set or customise the sort/filter proxy for the model in `_construct`:

```python

class MyFilesystemBrowser(FilesystemBrowser):
    '''FilesystemBrowser dialog.'''

   def _construct(self):
        '''Construct widget.'''
        super(MyFilesystemBrowser, self)._construct()
        model = self._filesystemWidget.model()
        # Do stuff with the model or use self._filesystemWidget.setModel to set a different one.
```
